# E.V. R11C FLAGSHIP REACTOR — AUTHORED HARD-SURFACE FORGE
# Generated by ChatGPT for the E.V. project.
# Blender 5.2 compatible.
#
# PURPOSE:
# - Build a coherent flagship reactor sculpture in Blender
# - Produce 5 static approval renders
# - Export authored GLB groups
# - Save .blend source
#
# IMPORTANT:
# - Does NOT modify D:\EV\gui
# - No QML integration until static renders are approved
#
# RUN:
#   "C:\Program Files\Blender Foundation\Blender 5.2\blender.exe" --background --python BUILD_R11C_FLAGSHIP_REACTOR.py

import bpy
import math
import os
from mathutils import Vector

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "output")
RENDERS = os.path.join(OUT, "renders")
ASSETS = os.path.join(OUT, "assets")
os.makedirs(RENDERS, exist_ok=True)
os.makedirs(ASSETS, exist_ok=True)

# -----------------------------------------------------------------------------
# SCENE
# -----------------------------------------------------------------------------

bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete(use_global=False)

scene = bpy.context.scene
scene.render.engine = "BLENDER_EEVEE"
scene.render.resolution_x = 1600
scene.render.resolution_y = 1000
scene.render.resolution_percentage = 100
scene.render.image_settings.file_format = "PNG"
scene.render.film_transparent = False

world = bpy.data.worlds.get("World") or bpy.data.worlds.new("World")
scene.world = world
world.use_nodes = True
bg = world.node_tree.nodes.get("Background")
bg.inputs["Color"].default_value = (0.0012, 0.0020, 0.0040, 1.0)
bg.inputs["Strength"].default_value = 0.045

# -----------------------------------------------------------------------------
# COLLECTIONS
# -----------------------------------------------------------------------------

def get_coll(name):
    c = bpy.data.collections.get(name)
    if c is None:
        c = bpy.data.collections.new(name)
        scene.collection.children.link(c)
    return c

C_SHELL   = get_coll("R11C_SHELL")
C_STATOR  = get_coll("R11C_STATOR")
C_CHAMBER = get_coll("R11C_CHAMBER")
C_IRIS    = get_coll("R11C_IRIS")
C_ENERGY  = get_coll("R11C_ENERGY")
C_DETAIL  = get_coll("R11C_DETAIL")

def move_to(obj, coll):
    for c in list(obj.users_collection):
        c.objects.unlink(obj)
    coll.objects.link(obj)

# -----------------------------------------------------------------------------
# MATERIALS
# -----------------------------------------------------------------------------

def mat_principled(name, rgb, metallic=0.0, roughness=0.35):
    m = bpy.data.materials.new(name)
    m.use_nodes = True
    bsdf = m.node_tree.nodes.get("Principled BSDF")
    bsdf.inputs["Base Color"].default_value = (*rgb, 1.0)
    bsdf.inputs["Metallic"].default_value = metallic
    bsdf.inputs["Roughness"].default_value = roughness
    return m

def mat_emission(name, rgb, strength=5.0):
    m = bpy.data.materials.new(name)
    m.use_nodes = True
    nt = m.node_tree
    nt.nodes.clear()
    out = nt.nodes.new("ShaderNodeOutputMaterial")
    em = nt.nodes.new("ShaderNodeEmission")
    em.inputs["Color"].default_value = (*rgb, 1.0)
    em.inputs["Strength"].default_value = strength
    nt.links.new(em.outputs["Emission"], out.inputs["Surface"])
    return m

def mat_glass(name, rgb=(0.03,0.07,0.11), roughness=0.07, ior=1.46):
    m = bpy.data.materials.new(name)
    m.use_nodes = True
    nt = m.node_tree
    nt.nodes.clear()
    out = nt.nodes.new("ShaderNodeOutputMaterial")
    g = nt.nodes.new("ShaderNodeBsdfGlass")
    g.inputs["Color"].default_value = (*rgb, 1.0)
    g.inputs["Roughness"].default_value = roughness
    g.inputs["IOR"].default_value = ior
    nt.links.new(g.outputs["BSDF"], out.inputs["Surface"])
    return m

M_GRAPHITE  = mat_principled("R11C_Graphite", (0.015,0.022,0.033), 0.86, 0.24)
M_GRAPHITE2 = mat_principled("R11C_Graphite2", (0.040,0.055,0.075), 0.80, 0.30)
M_TITANIUM  = mat_principled("R11C_Titanium", (0.27,0.34,0.43), 0.92, 0.18)
M_EDGE      = mat_principled("R11C_Edge", (0.52,0.60,0.69), 0.94, 0.15)
M_COPPER    = mat_principled("R11C_Copper", (0.10,0.026,0.008), 0.82, 0.26)
M_CERAMIC   = mat_principled("R11C_BlackCeramic", (0.004,0.007,0.011), 0.18, 0.15)
M_GLASS     = mat_glass("R11C_SmokedGlass")
M_ICE       = mat_emission("R11C_IceWhite", (0.60,0.88,1.0), 9.0)
M_CYAN      = mat_emission("R11C_Cyan", (0.02,0.30,0.72), 4.0)
M_AMBER     = mat_emission("R11C_Amber", (1.0,0.12,0.02), 1.8)

# -----------------------------------------------------------------------------
# HELPERS
# -----------------------------------------------------------------------------

def bevel(obj, width=0.05, segments=3):
    mod = obj.modifiers.new("PrecisionBevel", "BEVEL")
    mod.width = width
    mod.segments = segments
    mod.limit_method = "ANGLE"
    mod.angle_limit = math.radians(22)

def weighted(obj):
    try:
        mod = obj.modifiers.new("WeightedNormal", "WEIGHTED_NORMAL")
        mod.keep_sharp = True
    except Exception:
        pass

def smooth(obj):
    if hasattr(obj.data, "polygons"):
        for p in obj.data.polygons:
            p.use_smooth = True

def cube(name, loc, size, mat, coll, rot=(0,0,0), bv=0.05):
    bpy.ops.mesh.primitive_cube_add(location=loc, rotation=rot)
    o = bpy.context.object
    o.name = name
    o.scale = (size[0]/2, size[1]/2, size[2]/2)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    o.data.materials.append(mat)
    bevel(o, min(bv, min(size)*0.18), 3)
    weighted(o)
    move_to(o, coll)
    return o

def cyl(name, radius, depth, loc, mat, coll, verts=96, bv=0.035):
    bpy.ops.mesh.primitive_cylinder_add(vertices=verts, radius=radius, depth=depth, location=loc)
    o = bpy.context.object
    o.name = name
    o.data.materials.append(mat)
    bevel(o, bv, 3)
    weighted(o)
    smooth(o)
    move_to(o, coll)
    return o

def sphere(name, radius, loc, mat, coll, scale=(1,1,1), seg=64, rings=40):
    bpy.ops.mesh.primitive_uv_sphere_add(segments=seg, ring_count=rings, radius=radius, location=loc)
    o = bpy.context.object
    o.name = name
    o.scale = scale
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    o.data.materials.append(mat)
    smooth(o)
    move_to(o, coll)
    return o

def torus(name, major, minor, loc, mat, coll, major_seg=96, minor_seg=20):
    bpy.ops.mesh.primitive_torus_add(
        major_radius=major,
        minor_radius=minor,
        major_segments=major_seg,
        minor_segments=minor_seg,
        location=loc
    )
    o = bpy.context.object
    o.name = name
    o.data.materials.append(mat)
    smooth(o)
    move_to(o, coll)
    return o

def sculpted_shell(name, a0_deg, a1_deg, r_inner, r_outer, depth, z_front, z_back,
                   mat, coll, steps=72, camber=0.22, taper=0.08, skew=0.0):
    """
    Coherent cambered shell sector.
    Not a flat annular wedge:
    - front/back Z vary through the span
    - radii vary through the span
    - taper/skew break perfect circularity
    """
    a0 = math.radians(a0_deg)
    a1 = math.radians(a1_deg)
    verts = []
    faces = []

    # Four strips: front inner/outer, rear inner/outer
    for side in ("front","rear"):
        for i in range(steps+1):
            t = i/steps
            a = a0 + (a1-a0)*t
            wave = math.sin(math.pi*t)
            asym = (t-0.5)
            ri = r_inner * (1.0 - taper*wave + skew*asym)
            ro = r_outer * (1.0 + 0.45*taper*wave + 0.55*skew*asym)
            zbase = z_front if side=="front" else z_back
            z = zbase + (camber*wave if side=="front" else -0.55*camber*wave)
            verts.append((ri*math.cos(a), ri*math.sin(a), z))
            verts.append((ro*math.cos(a), ro*math.sin(a), z))

    n = (steps+1)*2
    # front/back faces
    for i in range(steps):
        b=i*2
        faces.append((b,b+1,b+3,b+2))
        t=n+i*2
        faces.append((t,t+2,t+3,t+1))
    # inner/outer walls
    for i in range(steps):
        b=i*2; t=n+i*2
        faces.append((b,b+2,t+2,t))
        faces.append((b+1,t+1,t+3,b+3))
    # end caps
    faces.append((0,n,n+1,1))
    e=steps*2
    faces.append((e,e+1,n+e+1,n+e))

    me=bpy.data.meshes.new(name+"_mesh")
    me.from_pydata(verts,[],faces)
    me.update()
    o=bpy.data.objects.new(name,me)
    coll.objects.link(o)
    o.data.materials.append(mat)
    bevel(o,0.055,3)
    weighted(o)
    smooth(o)
    return o

def radial_box(name, angle_deg, radius, tangential, radial, depth, z, mat, coll, angle_bias=0):
    a=math.radians(angle_deg)
    x=radius*math.cos(a); y=radius*math.sin(a)
    return cube(
        name,(x,y,z),(tangential,radial,depth),mat,coll,
        rot=(0,0,a-math.pi/2+math.radians(angle_bias)),
        bv=min(0.065,min(tangential,radial,depth)*0.14)
    )

# -----------------------------------------------------------------------------
# R11C FORM — 3 MAJOR SCULPTED MASSES + DEEP CHAMBER
# -----------------------------------------------------------------------------

# The signature is not a ring. It is 3 interlocking containment masses.
# Each mass has different radius, thickness, camber, and depth.

sculpted_shell("Shell_A", 18, 132, 3.45, 5.05, 0.90, 0.72, -0.30,
               M_GRAPHITE, C_SHELL, steps=90, camber=0.34, taper=0.10, skew=0.05)

sculpted_shell("Shell_B", 149, 247, 3.62, 4.92, 0.84, 0.38, -0.58,
               M_GRAPHITE2, C_SHELL, steps=82, camber=0.26, taper=0.07, skew=-0.04)

sculpted_shell("Shell_C", 268, 356, 3.28, 5.18, 1.04, 0.94, -0.16,
               M_GRAPHITE, C_SHELL, steps=78, camber=0.38, taper=0.11, skew=0.035)

# Front armor lands, small and embedded
sculpted_shell("Shell_A_Land", 34, 96, 4.18, 4.72, 0.17, 1.08, 0.90,
               M_TITANIUM, C_SHELL, steps=44, camber=0.08, taper=0.03, skew=0.02)
sculpted_shell("Shell_C_Land", 292, 336, 4.05, 4.70, 0.18, 1.22, 1.00,
               M_TITANIUM, C_SHELL, steps=38, camber=0.07, taper=0.02, skew=-0.02)

# Deep rear stator cage — partial, irregular, deliberately visible through gaps
for idx,(a0,a1,zin,zout) in enumerate([
    (2,58,-2.25,-1.65),(76,125,-2.05,-1.48),(142,196,-2.32,-1.70),
    (218,266,-2.12,-1.55),(284,342,-2.28,-1.62)
]):
    sculpted_shell(f"RearStator_{idx}", a0,a1,2.62,3.42,0.42,zout,zin,
                   M_CERAMIC,C_STATOR,steps=42,camber=0.08,taper=0.03,skew=(idx-2)*0.008)

# Structural bridges tying shell to chamber (integrated, not floating boxes)
for i,(a,z) in enumerate([(36,-0.45),(88,-0.62),(182,-0.56),(228,-0.42),(314,-0.50)]):
    radial_box(f"Bridge_{i}",a,2.98,0.34,1.10,0.40,z,M_GRAPHITE2,C_STATOR,angle_bias=[5,-4,3,-6,4][i])

# Four engineered power spines rather than 8 box cassettes
spine_specs=[
    (54,3.32,0.72,1.18,0.82,0.74,-5),
    (126,3.18,0.64,1.08,0.76,0.58,4),
    (214,3.28,0.78,1.24,0.88,0.66,-4),
    (326,3.36,0.70,1.12,0.92,0.84,5),
]
for i,(a,r,tan,rad,dep,z,bias) in enumerate(spine_specs):
    radial_box(f"PowerSpine_{i}",a,r,tan,rad,dep,z,M_GRAPHITE2,C_DETAIL,angle_bias=bias)
    radial_box(f"PowerSpineCap_{i}",a,r-0.32,tan*0.66,rad*0.36,0.12,z+dep*0.56,M_TITANIUM,C_DETAIL,angle_bias=bias)
    # inset dark copper conductors
    for j,off in enumerate((-0.12,0.12)):
        aa=math.radians(a)
        tx=-math.sin(aa); ty=math.cos(aa)
        x=(r+0.22)*math.cos(aa)+tx*off
        y=(r+0.22)*math.sin(aa)+ty*off
        cube(f"SpineCopper_{i}_{j}",(x,y,z-0.44),(0.055,0.56,0.11),M_COPPER,C_DETAIL,rot=(0,0,aa),bv=0.010)

# -----------------------------------------------------------------------------
# CHAMBER — VISIBLE DEPTH, NO FLAT DISC
# -----------------------------------------------------------------------------

# Rear cavity and mechanical throat
cyl("ChamberRearBody",1.62,0.70,(0,0,-1.92),M_CERAMIC,C_CHAMBER,verts=128,bv=0.035)
torus("RearContainmentRing",1.20,0.075,(0,0,-1.54),M_CYAN,C_ENERGY,major_seg=128,minor_seg=18)

# Mechanical iris blades at staggered Z
iris_angles=[12,72,132,192,252,312]
for i,a in enumerate(iris_angles):
    radial_box(f"IrisBlade_{i}",a,1.62,0.34,0.82,0.22,0.30+(i%2)*0.10,M_TITANIUM,C_IRIS,angle_bias=[7,-5,6,-7,4,-5][i])

# Smoked lens at front
cyl("SmokedLens",1.18,0.18,(0,0,0.86),M_GLASS,C_CHAMBER,verts=128,bv=0.018)

# White confinement is a thin torus, not a circle fill
torus("ConfinementField",0.88,0.070,(0.02,-0.02,0.50),M_ICE,C_ENERGY,major_seg=128,minor_seg=18)

# Plasma is a translucent-looking volume behind it
sphere("PlasmaVolume",0.72,(0.04,-0.03,0.10),M_CYAN,C_CHAMBER,scale=(1.0,1.0,0.52),seg=72,rings=44)

# Dark cognition nucleus
sphere("CognitionNucleus",0.35,(-0.05,0.02,-0.42),M_CERAMIC,C_CHAMBER,scale=(0.92,1.10,1.02),seg=64,rings=40)

# Tiny deep pin light
sphere("DeepPin",0.055,(0.12,-0.05,-0.96),M_ICE,C_ENERGY,seg=28,rings=18)

# Partial front retaining bezel — 4 pieces only
for i,(a0,a1,z) in enumerate([(8,56,1.16),(88,130,1.10),(184,232,1.12),(286,330,1.18)]):
    sculpted_shell(f"FrontBezel_{i}",a0,a1,1.88,2.08,0.18,z,z-0.16,M_EDGE,C_IRIS,
                   steps=34,camber=0.025,taper=0.015,skew=0.01)

# Controlled energy seams — very small total luminous area
for i,(a0,a1,mat,z) in enumerate([
    (20,36,M_ICE,0.93),
    (102,118,M_CYAN,0.82),
    (212,228,M_ICE,0.88),
    (304,316,M_AMBER,0.84),
]):
    sculpted_shell(f"EnergySeam_{i}",a0,a1,1.00,1.10,0.050,z,z-0.05,mat,C_ENERGY,
                   steps=18,camber=0.008,taper=0.0,skew=0.0)

# Sparse cognition nodes
for i,(a,r,z,sz) in enumerate([(28,0.60,0.73,0.034),(118,0.50,0.54,0.027),(208,0.66,0.34,0.029),(316,0.58,0.46,0.026)]):
    aa=math.radians(a)
    sphere(f"Node_{i}",sz,(r*math.cos(aa),r*math.sin(aa),z),M_ICE,C_DETAIL,seg=28,rings=18)

# -----------------------------------------------------------------------------
# LIGHTING
# -----------------------------------------------------------------------------

def look_at(obj,target=(0,0,-0.30)):
    obj.rotation_euler=(Vector(target)-obj.location).to_track_quat("-Z","Y").to_euler()

def area(name,loc,energy,color,size):
    d=bpy.data.lights.new(name,"AREA")
    d.energy=energy; d.color=color; d.shape="DISK"; d.size=size
    o=bpy.data.objects.new(name,d); scene.collection.objects.link(o); o.location=loc; look_at(o)
    return o

def point(name,loc,energy,color,size):
    d=bpy.data.lights.new(name,"POINT")
    d.energy=energy; d.color=color; d.shadow_soft_size=size
    o=bpy.data.objects.new(name,d); scene.collection.objects.link(o); o.location=loc
    return o

area("Key",(-5.4,-6.2,8.8),1120,(0.72,0.84,1.0),4.0)
area("Fill",(5.5,-3.0,3.5),310,(0.20,0.31,0.50),4.5)
area("Rim",(4.8,5.0,-3.0),1280,(0.66,0.82,1.0),3.1)
point("Internal",(0,0,1.4),190,(0.04,0.25,1.0),0.65)
point("WarmMicro",(3.4,-1.4,0.7),38,(1.0,0.10,0.02),0.45)

# -----------------------------------------------------------------------------
# CAMERA / RENDERS
# -----------------------------------------------------------------------------

cam_data=bpy.data.cameras.new("R11C_Camera")
cam=bpy.data.objects.new("R11C_Camera",cam_data)
scene.collection.objects.link(cam)
scene.camera=cam
cam.data.sensor_width=36

def render(name,loc,target=(0,0,-0.35),lens=70):
    cam.location=loc
    cam.data.lens=lens
    look_at(cam,target)
    scene.render.filepath=os.path.join(RENDERS,name)
    bpy.ops.render.render(write_still=True)

render("R11C_FRONT.png",(0,-0.6,17.5),lens=74)
render("R11C_PRIMARY_3Q.png",(5.6,-5.6,15.2),target=(0,0,-0.45),lens=72)
render("R11C_OPPOSITE_3Q.png",(-5.8,5.0,14.8),target=(0,0,-0.55),lens=72)
render("R11C_SIDE_DEPTH.png",(12.8,-0.8,8.4),target=(0,0,-0.80),lens=76)

saved={}
for o in scene.objects:
    if o.type=="LIGHT":
        saved[o.name]=o.data.energy
        if o.name in ("Key","Fill","Rim"):
            o.data.energy*=0.26
        elif o.name=="Internal":
            o.data.energy*=1.40
render("R11C_DARK_ENERGY.png",(5.6,-5.6,15.2),target=(0,0,-0.45),lens=72)
for o in scene.objects:
    if o.type=="LIGHT" and o.name in saved:
        o.data.energy=saved[o.name]

# -----------------------------------------------------------------------------
# SAVE / EXPORT
# -----------------------------------------------------------------------------

blend_path=os.path.join(OUT,"R11C_FLAGSHIP_REACTOR_SOURCE.blend")
bpy.ops.wm.save_as_mainfile(filepath=blend_path)

def export_collection(coll,filename):
    bpy.ops.object.select_all(action="DESELECT")
    objs=[o for o in coll.all_objects if o.type in {"MESH","EMPTY"}]
    for o in objs: o.select_set(True)
    if not objs: return
    bpy.context.view_layer.objects.active=objs[0]
    bpy.ops.export_scene.gltf(
        filepath=os.path.join(ASSETS,filename),
        export_format="GLB",
        use_selection=True,
        export_apply=True,
        export_yup=True
    )

exports=[
    (C_SHELL,"ev_core_r11c_shell.glb"),
    (C_STATOR,"ev_core_r11c_stator.glb"),
    (C_CHAMBER,"ev_core_r11c_chamber.glb"),
    (C_IRIS,"ev_core_r11c_iris.glb"),
    (C_ENERGY,"ev_core_r11c_energy.glb"),
    (C_DETAIL,"ev_core_r11c_detail.glb"),
]
for c,f in exports:
    export_collection(c,f)

# triangle count
dg=bpy.context.evaluated_depsgraph_get()
tris=0
for o in scene.objects:
    if o.type=="MESH":
        ev=o.evaluated_get(dg)
        me=ev.to_mesh()
        me.calc_loop_triangles()
        tris+=len(me.loop_triangles)
        ev.to_mesh_clear()

report=os.path.join(OUT,"R11C_BUILD_REPORT.txt")
with open(report,"w",encoding="utf-8") as f:
    f.write("E.V. R11C FLAGSHIP REACTOR BUILD REPORT\n")
    f.write("=====================================\n\n")
    f.write(f"Blender: {bpy.app.version_string}\n")
    f.write(f"Evaluated triangles: {tris}\n")
    f.write("Live E.V. GUI modified: NO\n")
    f.write("Major design: 3 interlocking sculpted masses, deep chamber, 4 power spines.\n\n")
    f.write("Renders:\n")
    for n in ["R11C_FRONT.png","R11C_PRIMARY_3Q.png","R11C_OPPOSITE_3Q.png","R11C_SIDE_DEPTH.png","R11C_DARK_ENERGY.png"]:
        f.write("- "+os.path.join(RENDERS,n)+"\n")
    f.write("\nAssets:\n")
    for _,n in exports:
        p=os.path.join(ASSETS,n)
        f.write(f"- {p} ({os.path.getsize(p) if os.path.exists(p) else 0} bytes)\n")

print("\nR11C FLAGSHIP REACTOR COMPLETE")
print("Blend:",blend_path)
print("Triangle count:",tris)
print("Renders:",RENDERS)
print("Assets:",ASSETS)
print("Report:",report)
