# E.V. R11 VECTOR REACTOR - Blender authored asset forge
# Generated by ChatGPT for D:\EV
# Purpose: build a static flagship reactor model OUTSIDE the live EV project,
# render 5 approval views, export authored GLB groups, and save the .blend source.
#
# Run with Blender:
#   blender.exe --background --python BUILD_R11_VECTOR_REACTOR.py
#
# This script does NOT touch D:\EV\gui. It writes only inside its output directory.

import bpy
import bmesh
import math
import os
from mathutils import Vector

# ---------------------------------------------------------------------------
# OUTPUT
# ---------------------------------------------------------------------------

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SCRIPT_DIR, "output")
RENDER_DIR = os.path.join(OUT_DIR, "renders")
ASSET_DIR = os.path.join(OUT_DIR, "assets")
os.makedirs(RENDER_DIR, exist_ok=True)
os.makedirs(ASSET_DIR, exist_ok=True)

# ---------------------------------------------------------------------------
# SCENE RESET / RENDER CONFIG
# ---------------------------------------------------------------------------

bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)

for datablocks in (
    bpy.data.meshes,
    bpy.data.curves,
    bpy.data.cameras,
    bpy.data.lights,
):
    # Leave material cleanup to Blender.
    pass

scene = bpy.context.scene
scene.render.resolution_x = 1600
scene.render.resolution_y = 1000
scene.render.resolution_percentage = 100
scene.render.image_settings.file_format = 'PNG'
scene.render.film_transparent = False

# Eevee version compatibility.
try:
    scene.render.engine = 'BLENDER_EEVEE_NEXT'
except Exception:
    scene.render.engine = 'BLENDER_EEVEE'

scene.render.image_settings.color_mode = 'RGBA'
scene.render.image_settings.color_depth = '8'

# World
world = bpy.data.worlds.get("World")
if world is None:
    world = bpy.data.worlds.new("World")
scene.world = world
world.use_nodes = True
bg = world.node_tree.nodes.get("Background")
bg.inputs["Color"].default_value = (0.0025, 0.0045, 0.008, 1.0)
bg.inputs["Strength"].default_value = 0.10

# ---------------------------------------------------------------------------
# HELPERS
# ---------------------------------------------------------------------------

def collection(name):
    c = bpy.data.collections.get(name)
    if c is None:
        c = bpy.data.collections.new(name)
        scene.collection.children.link(c)
    return c

COL_FRAME = collection("R11_FRAME")
COL_STATOR = collection("R11_STATOR")
COL_FLUX = collection("R11_FLUX")
COL_COILS = collection("R11_COILS")
COL_LENS = collection("R11_LENS")
COL_BEZEL = collection("R11_BEZEL")
COL_ENERGY = collection("R11_ENERGY")
COL_NODES = collection("R11_NODES")

ALL_ASSET_COLLECTIONS = [
    COL_FRAME, COL_STATOR, COL_FLUX, COL_COILS,
    COL_LENS, COL_BEZEL, COL_ENERGY, COL_NODES
]

def move_to_collection(obj, coll):
    for c in list(obj.users_collection):
        c.objects.unlink(obj)
    coll.objects.link(obj)

def mat_principled(name, base, metallic=0.0, roughness=0.4):
    m = bpy.data.materials.new(name)
    m.use_nodes = True
    nt = m.node_tree
    for n in nt.nodes:
        nt.nodes.remove(n)
    out = nt.nodes.new("ShaderNodeOutputMaterial")
    bsdf = nt.nodes.new("ShaderNodeBsdfPrincipled")
    bsdf.inputs.get("Base Color").default_value = (*base, 1.0)
    if bsdf.inputs.get("Metallic"):
        bsdf.inputs["Metallic"].default_value = metallic
    if bsdf.inputs.get("Roughness"):
        bsdf.inputs["Roughness"].default_value = roughness
    nt.links.new(bsdf.outputs["BSDF"], out.inputs["Surface"])
    return m

def mat_emission(name, color, strength=5.0):
    m = bpy.data.materials.new(name)
    m.use_nodes = True
    nt = m.node_tree
    for n in nt.nodes:
        nt.nodes.remove(n)
    out = nt.nodes.new("ShaderNodeOutputMaterial")
    em = nt.nodes.new("ShaderNodeEmission")
    em.inputs["Color"].default_value = (*color, 1.0)
    em.inputs["Strength"].default_value = strength
    nt.links.new(em.outputs["Emission"], out.inputs["Surface"])
    return m

def mat_glass(name, color=(0.10, 0.16, 0.22), roughness=0.12, ior=1.45):
    m = bpy.data.materials.new(name)
    m.use_nodes = True
    nt = m.node_tree
    for n in nt.nodes:
        nt.nodes.remove(n)
    out = nt.nodes.new("ShaderNodeOutputMaterial")
    glass = nt.nodes.new("ShaderNodeBsdfGlass")
    glass.inputs["Color"].default_value = (*color, 1.0)
    glass.inputs["Roughness"].default_value = roughness
    glass.inputs["IOR"].default_value = ior
    nt.links.new(glass.outputs["BSDF"], out.inputs["Surface"])
    return m

MAT_GRAPHITE = mat_principled("Graphite", (0.035, 0.050, 0.070), 0.78, 0.28)
MAT_GRAPHITE_2 = mat_principled("GraphiteSecondary", (0.065, 0.085, 0.110), 0.70, 0.32)
MAT_TITANIUM = mat_principled("Titanium", (0.32, 0.38, 0.46), 0.88, 0.22)
MAT_EDGE = mat_principled("PrecisionEdge", (0.56, 0.64, 0.72), 0.90, 0.18)
MAT_COPPER = mat_principled("DarkCopper", (0.18, 0.070, 0.025), 0.76, 0.30)
MAT_GLASS = mat_glass("SmokedContainmentGlass")
MAT_ICE = mat_emission("IceWhiteEnergy", (0.68, 0.88, 1.00), 9.0)
MAT_CYAN = mat_emission("CyanEnergy", (0.04, 0.42, 0.78), 5.0)
MAT_AMBER = mat_emission("AmberAccent", (1.00, 0.22, 0.035), 3.0)
MAT_NUCLEUS = mat_principled("DarkNucleus", (0.008, 0.015, 0.025), 0.55, 0.18)

def add_bevel(obj, width=0.06, segments=3):
    mod = obj.modifiers.new(name="PrecisionBevel", type='BEVEL')
    mod.width = width
    mod.segments = segments
    mod.limit_method = 'ANGLE'
    mod.angle_limit = math.radians(22)
    return mod

def add_weighted_normal(obj):
    try:
        mod = obj.modifiers.new(name="WeightedNormals", type='WEIGHTED_NORMAL')
        mod.keep_sharp = True
    except Exception:
        pass

def shade_smooth_angle(obj, angle=math.radians(38)):
    if not hasattr(obj.data, "polygons"):
        return
    for p in obj.data.polygons:
        p.use_smooth = True
    # Blender 4 removed use_auto_smooth. Bevel + weighted normals handle it.

def add_cube(name, loc, scale, mat, coll, bevel=0.06, rot=(0,0,0)):
    bpy.ops.mesh.primitive_cube_add(location=loc, rotation=rot)
    o = bpy.context.active_object
    o.name = name
    o.scale = scale
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    if mat:
        o.data.materials.append(mat)
    add_bevel(o, bevel, 3)
    add_weighted_normal(o)
    move_to_collection(o, coll)
    return o

def add_cylinder(name, radius, depth, loc, mat, coll, verts=96, rot=(0,0,0), bevel=0.04):
    bpy.ops.mesh.primitive_cylinder_add(vertices=verts, radius=radius, depth=depth, location=loc, rotation=rot)
    o = bpy.context.active_object
    o.name = name
    if mat:
        o.data.materials.append(mat)
    add_bevel(o, bevel, 3)
    add_weighted_normal(o)
    shade_smooth_angle(o)
    move_to_collection(o, coll)
    return o

def add_uv_sphere(name, radius, loc, mat, coll, scale=(1,1,1)):
    bpy.ops.mesh.primitive_uv_sphere_add(segments=96, ring_count=64, radius=radius, location=loc)
    o = bpy.context.active_object
    o.name = name
    o.scale = scale
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    if mat:
        o.data.materials.append(mat)
    shade_smooth_angle(o)
    move_to_collection(o, coll)
    return o

def arc_prism(name, r0, r1, a0_deg, a1_deg, depth, z, mat, coll,
              steps=48, bevel=0.055, y_offset=0.0, skew=0.0):
    """
    Annular sector in XY with thickness along Z.
    Adds slight radial skew to avoid perfect HUD-ring purity.
    """
    a0 = math.radians(a0_deg)
    a1 = math.radians(a1_deg)
    verts = []
    faces = []

    for side_z in (-depth/2.0, depth/2.0):
        for i in range(steps + 1):
            t = i / steps
            a = a0 + (a1-a0) * t
            # small authored asymmetry
            ripple = 1.0 + skew * math.sin(t * math.pi)
            ro = r1 * ripple
            ri = r0 * (1.0 - 0.35 * skew * math.sin(t * math.pi))
            verts.append((ri*math.cos(a), ri*math.sin(a)+y_offset, z+side_z))
            verts.append((ro*math.cos(a), ro*math.sin(a)+y_offset, z+side_z))

    ring_count = steps + 1
    bottom = 0
    top = ring_count * 2

    # front/back
    for i in range(steps):
        i0 = bottom + i*2
        i1 = i0 + 2
        faces.append((i0, i0+1, i1+1, i1))
        j0 = top + i*2
        j1 = j0 + 2
        faces.append((j0, j1, j1+1, j0+1))

    # inner / outer walls
    for i in range(steps):
        b0 = bottom + i*2
        b1 = b0 + 2
        t0 = top + i*2
        t1 = t0 + 2
        faces.append((b0, b1, t1, t0))

        b0o = bottom + i*2 + 1
        b1o = b0o + 2
        t0o = top + i*2 + 1
        t1o = t0o + 2
        faces.append((b0o, t0o, t1o, b1o))

    # end caps
    faces.append((bottom, top, top+1, bottom+1))
    e_b = bottom + steps*2
    e_t = top + steps*2
    faces.append((e_b, e_b+1, e_t+1, e_t))

    mesh = bpy.data.meshes.new(name+"_mesh")
    mesh.from_pydata(verts, [], faces)
    mesh.update()
    o = bpy.data.objects.new(name, mesh)
    coll.objects.link(o)
    if mat:
        o.data.materials.append(mat)
    add_bevel(o, bevel, 3)
    add_weighted_normal(o)
    shade_smooth_angle(o)
    return o

def radial_box(name, angle_deg, radius, tangential, radial, depth, z, mat, coll,
               angle_offset_deg=0.0, radial_offset=0.0):
    a = math.radians(angle_deg)
    r = radius + radial_offset
    x, y = r*math.cos(a), r*math.sin(a)
    # local X=tangential, Y=radial, Z=depth
    o = add_cube(
        name,
        (x, y, z),
        (tangential/2.0, radial/2.0, depth/2.0),
        mat,
        coll,
        bevel=min(0.075, min(tangential, radial, depth)*0.12),
        rot=(0,0,a - math.pi/2.0 + math.radians(angle_offset_deg))
    )
    return o

# ---------------------------------------------------------------------------
# MODEL
# ---------------------------------------------------------------------------

# Global dimensions are intentionally non-Marvel and not perfectly symmetric.
R_OUT = 4.70
R_FRAME_IN = 3.70
R_FLUX = 2.95
R_LENS = 1.62

# HEAVY OUTER FRAME - asymmetric sector construction
frame_specs = [
    # a0, a1, depth, z, material, skew
    (18, 84, 0.72, -0.15, MAT_GRAPHITE, 0.045),
    (96, 160, 0.84, +0.04, MAT_GRAPHITE, 0.065),  # heavier upper-left
    (170, 226, 0.68, -0.26, MAT_GRAPHITE_2, 0.025),
    (239, 302, 0.92, +0.28, MAT_GRAPHITE, 0.055), # advanced lower-right
    (315, 360, 0.66, -0.08, MAT_GRAPHITE_2, 0.030),
]
for i, (a0,a1,d,z,mat,skew) in enumerate(frame_specs):
    arc_prism(f"FrameSector_{i}", R_FRAME_IN, R_OUT, a0, a1, d, z,
              mat, COL_FRAME, steps=64, bevel=0.075, skew=skew)

# Raised precision faces on selected frame regions
for i, (a0,a1,z) in enumerate([
    (29, 70, 0.42),
    (108, 146, 0.48),
    (251, 290, 0.63),
]):
    arc_prism(f"FrameInset_{i}", 4.05, 4.53, a0, a1, 0.16, z,
              MAT_TITANIUM, COL_FRAME, steps=40, bevel=0.035, skew=0.02)

# Subtle E/V directional structural signature (non-logo)
radial_box("EV_Cut_Inward", 132, 4.22, 0.18, 1.18, 0.19, 0.57, MAT_EDGE, COL_FRAME, angle_offset_deg=+16)
radial_box("EV_Cut_Bifurcated_A", 324, 4.10, 0.15, 0.92, 0.17, 0.49, MAT_EDGE, COL_FRAME, angle_offset_deg=-12)
radial_box("EV_Cut_Bifurcated_B", 337, 4.13, 0.13, 0.78, 0.15, 0.44, MAT_EDGE, COL_FRAME, angle_offset_deg=+10)

# REAR STATOR at substantial negative depth
for i, (a0,a1) in enumerate([(8,52),(62,101),(114,155),(166,205),(217,258),(271,312),(324,354)]):
    arc_prism(f"StatorArc_{i}", 3.18, 4.12, a0, a1, 0.42, -1.40,
              MAT_GRAPHITE_2, COL_STATOR, steps=42, bevel=0.045, skew=0.018)

# stator ribs
for idx, a in enumerate([7, 34, 67, 97, 129, 158, 192, 225, 261, 296, 327, 351]):
    radial_box(f"StatorRib_{idx}", a, 3.58, 0.13, 1.05, 0.24, -1.14,
               MAT_TITANIUM, COL_STATOR, angle_offset_deg=(idx%3-1)*4)

# FLUX CASSETTES - 8 original, nonidentical, physically forward of stator
flux_angles = [5, 48, 92, 139, 183, 229, 276, 323]
for i, a in enumerate(flux_angles):
    radial_len = [0.88,1.10,0.96,1.20,0.84,1.12,1.00,0.92][i]
    tangential = [0.52,0.46,0.56,0.48,0.58,0.50,0.44,0.54][i]
    depth = [0.62,0.70,0.58,0.76,0.64,0.68,0.60,0.72][i]
    z = [0.32,0.46,0.26,0.54,0.30,0.42,0.24,0.50][i]
    off = [0.0,0.08,-0.05,0.10,-0.06,0.04,-0.08,0.06][i]
    o = radial_box(f"FluxCassette_{i}", a, R_FLUX, tangential, radial_len, depth, z,
                   MAT_GRAPHITE_2, COL_FLUX, angle_offset_deg=[-6,4,0,7,-5,3,-4,5][i],
                   radial_offset=off)
    # inset metallic face
    face_r = R_FLUX + off - radial_len*0.20
    radial_box(f"FluxFace_{i}", a, face_r, tangential*0.72, radial_len*0.50, 0.12, z+depth*0.54,
               MAT_TITANIUM, COL_FLUX, angle_offset_deg=[-6,4,0,7,-5,3,-4,5][i])

# COILS - darker copper architecture behind cassettes
for i, a in enumerate(flux_angles):
    # two narrow copper bars per cassette, positioned deeper
    for j, da in enumerate((-3.2, 3.2)):
        radial_box(f"CoilBar_{i}_{j}", a+da, 2.75, 0.080, 0.92, 0.14, -0.72,
                   MAT_COPPER, COL_COILS, angle_offset_deg=(j*2-1)*4)

# LENS HOUSING
arc_prism("LensHousingTop", 1.72, 2.18, 8, 176, 0.50, 0.48, MAT_GRAPHITE, COL_LENS, steps=70, bevel=0.060, skew=0.02)
arc_prism("LensHousingBottom", 1.72, 2.18, 191, 350, 0.54, 0.44, MAT_GRAPHITE_2, COL_LENS, steps=70, bevel=0.060, skew=0.025)

# Smoked containment lens volume (multiple depths, not a flat disc)
add_cylinder("LensGlassFront", 1.60, 0.20, (0,0,0.55), MAT_GLASS, COL_LENS, verts=128, bevel=0.025)
add_uv_sphere("PlasmaField", 1.28, (0.05,-0.04,0.22), MAT_ICE, COL_LENS, scale=(1.0,1.0,0.42))
add_uv_sphere("StatePlasma", 0.86, (-0.08,0.05,-0.10), MAT_CYAN, COL_LENS, scale=(1.0,1.0,0.52))
add_uv_sphere("DarkCognitionNucleus", 0.46, (0.06,-0.05,-0.55), MAT_NUCLEUS, COL_LENS, scale=(0.92,1.08,0.88))

# Rear glow cavity
add_cylinder("RearGlowCavity", 1.08, 0.16, (0,0,-1.12), MAT_CYAN, COL_LENS, verts=96, bevel=0.02)

# BEZEL - segmented foreground precision frame, intentionally incomplete
for i, (a0,a1,z) in enumerate([(2,54,1.05),(71,124,1.12),(145,198,0.98),(220,271,1.18),(294,342,1.04)]):
    arc_prism(f"Bezel_{i}", 2.23, 2.42, a0, a1, 0.20, z,
              MAT_EDGE, COL_BEZEL, steps=42, bevel=0.025, skew=0.012)

# ENERGY - no full ring; segmented emitters only
energy_segments = [
    (12, 42, MAT_ICE, 0.84),
    (58, 86, MAT_CYAN, 0.76),
    (108, 138, MAT_ICE, 0.80),
    (161, 192, MAT_CYAN, 0.70),
    (213, 239, MAT_ICE, 0.78),
    (259, 286, MAT_CYAN, 0.68),
    (307, 331, MAT_AMBER, 0.62),
]
for i,(a0,a1,mat,z) in enumerate(energy_segments):
    arc_prism(f"EnergyArc_{i}", 1.44, 1.58, a0, a1, 0.09, z,
              mat, COL_ENERGY, steps=32, bevel=0.018, skew=0.008)

# Energy seams near a few cassettes
for i,a in enumerate([44, 138, 276]):
    radial_box(f"EnergySeam_{i}", a, 2.55, 0.055, 0.58, 0.045, 0.94,
               MAT_ICE if i < 2 else MAT_AMBER, COL_ENERGY)

# Sparse nodes
node_specs = [
    (0.62, 0.70, 0.92, 0.055),
    (-0.83, 0.38, 0.74, 0.040),
    (0.84,-0.54,0.64,0.046),
    (-0.52,-0.76,0.50,0.034),
    (1.18,0.10,0.24,0.032),
    (-1.04,-0.12,0.30,0.030),
]
for i,(x,y,z,r) in enumerate(node_specs):
    add_uv_sphere(f"CognitionNode_{i}", r, (x,y,z), MAT_ICE, COL_NODES)

# ---------------------------------------------------------------------------
# LIGHTING / CAMERA
# ---------------------------------------------------------------------------

def add_area(name, loc, energy, color, size):
    data = bpy.data.lights.new(name=name, type='AREA')
    data.energy = energy
    data.color = color
    data.shape = 'DISK'
    data.size = size
    obj = bpy.data.objects.new(name, data)
    scene.collection.objects.link(obj)
    obj.location = loc
    look_at(obj, (0,0,0))
    return obj

def add_point(name, loc, energy, color, radius=0.4):
    data = bpy.data.lights.new(name=name, type='POINT')
    data.energy = energy
    data.color = color
    data.shadow_soft_size = radius
    obj = bpy.data.objects.new(name, data)
    scene.collection.objects.link(obj)
    obj.location = loc
    return obj

def look_at(obj, target):
    direction = Vector(target) - obj.location
    obj.rotation_euler = direction.to_track_quat('-Z', 'Y').to_euler()

add_area("Key", (-4.5,-6.0,8.0), 900, (0.74,0.86,1.0), 5.0)
add_area("Fill", (5.5,-4.0,3.0), 420, (0.28,0.42,0.62), 4.0)
add_area("Rim", (5.0,3.0,-4.0), 1050, (0.72,0.86,1.0), 3.2)
add_point("InternalCool", (0,0,1.8), 240, (0.16,0.48,1.0), 1.0)
add_point("WarmAccent", (3.4,-1.0,1.0), 85, (1.0,0.18,0.03), 0.7)

# Camera
cam_data = bpy.data.cameras.new("R11_Camera")
cam = bpy.data.objects.new("R11_Camera", cam_data)
scene.collection.objects.link(cam)
scene.camera = cam
cam.data.lens = 58
cam.data.sensor_width = 36

# ---------------------------------------------------------------------------
# RENDER VIEWS
# ---------------------------------------------------------------------------

def render_view(filename, loc, target=(0,0,-0.15), lens=58):
    cam.location = loc
    cam.data.lens = lens
    look_at(cam, target)
    scene.render.filepath = os.path.join(RENDER_DIR, filename)
    bpy.ops.render.render(write_still=True)

# front - near-front but with slight elevation so thickness still reads
render_view("R11_FRONT.png", (0.0, -0.7, 13.5), target=(0,0,-0.15), lens=60)

# primary three-quarter
render_view("R11_PRIMARY_3Q.png", (4.6, -5.6, 11.0), target=(0,0,-0.20), lens=58)

# opposite three-quarter
render_view("R11_OPPOSITE_3Q.png", (-4.8, 4.8, 10.5), target=(0,0,-0.30), lens=58)

# depth / side
render_view("R11_SIDE_DEPTH.png", (10.5, -1.0, 5.2), target=(0,0,-0.30), lens=62)

# dark energy view: lower external light intensities temporarily
light_energy = {}
for obj in scene.objects:
    if obj.type == 'LIGHT':
        light_energy[obj.name] = obj.data.energy
        if obj.name in ("Key", "Fill", "Rim"):
            obj.data.energy *= 0.28
        elif obj.name == "InternalCool":
            obj.data.energy *= 1.30

render_view("R11_DARK_ENERGY.png", (4.6,-5.6,11.0), target=(0,0,-0.20), lens=58)

for obj in scene.objects:
    if obj.type == 'LIGHT' and obj.name in light_energy:
        obj.data.energy = light_energy[obj.name]

# ---------------------------------------------------------------------------
# SAVE BLEND / EXPORT GLB GROUPS
# ---------------------------------------------------------------------------

blend_path = os.path.join(OUT_DIR, "R11_VECTOR_REACTOR_SOURCE.blend")
bpy.ops.wm.save_as_mainfile(filepath=blend_path)

def export_collection_as_glb(coll, filename):
    bpy.ops.object.select_all(action='DESELECT')
    selected = []
    for obj in coll.all_objects:
        if obj.type in {'MESH', 'EMPTY'}:
            obj.select_set(True)
            selected.append(obj)
    if not selected:
        return
    bpy.context.view_layer.objects.active = selected[0]
    bpy.ops.export_scene.gltf(
        filepath=os.path.join(ASSET_DIR, filename),
        export_format='GLB',
        use_selection=True,
        export_apply=True,
        export_yup=True,
    )

exports = [
    (COL_FRAME, "ev_core_r11_frame.glb"),
    (COL_STATOR, "ev_core_r11_stator.glb"),
    (COL_FLUX, "ev_core_r11_flux.glb"),
    (COL_COILS, "ev_core_r11_coils.glb"),
    (COL_LENS, "ev_core_r11_lens.glb"),
    (COL_BEZEL, "ev_core_r11_bezel.glb"),
    (COL_ENERGY, "ev_core_r11_energy.glb"),
    (COL_NODES, "ev_core_r11_nodes.glb"),
]
for coll, filename in exports:
    export_collection_as_glb(coll, filename)

# ---------------------------------------------------------------------------
# REPORT
# ---------------------------------------------------------------------------

def mesh_triangles():
    total = 0
    for obj in scene.objects:
        if obj.type == 'MESH':
            # evaluated mesh count is expensive but accurate enough here
            dg = bpy.context.evaluated_depsgraph_get()
            ev = obj.evaluated_get(dg)
            me = ev.to_mesh()
            me.calc_loop_triangles()
            total += len(me.loop_triangles)
            ev.to_mesh_clear()
    return total

tri_count = mesh_triangles()

report_path = os.path.join(OUT_DIR, "R11_BUILD_REPORT.txt")
with open(report_path, "w", encoding="utf-8") as f:
    f.write("E.V. R11 VECTOR REACTOR BUILD REPORT\n")
    f.write("===================================\n\n")
    f.write(f"Blender version: {bpy.app.version_string}\n")
    f.write(f"Estimated evaluated triangle count: {tri_count}\n")
    f.write("Live EV project modified: NO\n\n")
    f.write("Renders:\n")
    for name in [
        "R11_FRONT.png",
        "R11_PRIMARY_3Q.png",
        "R11_OPPOSITE_3Q.png",
        "R11_SIDE_DEPTH.png",
        "R11_DARK_ENERGY.png",
    ]:
        f.write(f"- {os.path.join(RENDER_DIR, name)}\n")
    f.write("\nAssets:\n")
    for _, name in exports:
        p = os.path.join(ASSET_DIR, name)
        f.write(f"- {p} ({os.path.getsize(p) if os.path.exists(p) else 0} bytes)\n")

print("\nR11 VECTOR REACTOR COMPLETE")
print("Blend:", blend_path)
print("Triangle count:", tri_count)
print("Renders:", RENDER_DIR)
print("Assets:", ASSET_DIR)
print("Report:", report_path)
